name: Feature Change
description: Alteration, replacement, or partial removal of existing functionality
title: "feature-change: "
labels: ["feature-change"]
assignees: []
body:
  - type: textarea
    id: problem-motivation
    attributes:
      label: Problem/Motivation
      description: Describe your problem or motivation that caused your feature change request as detailed as possible.
      placeholder: Which needs does the feature not fulfill? Is something missing? Is it too complicated or convoluted?
    validations:
      required: true
  - type: textarea
    id: solution-proposal
    attributes:
      label: Solution Proposal
      description: Describe the solution that you have in mind as detailed as possible.
      placeholder: How could the feature be made more useful? How could the feature be simplified? How should the feature work after the changes are applied? How should the changes be integrated?
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe potential side effects of your solution proposal, which could cause follow-up issues (in particular feature changes or feature drops), to the best of your knowledge.
      placeholder: Could my solution proposal cause other problems?
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specify the acceptance criteria as a task list that contains one or more entries.
      placeholder: |
        - [ ] Do this
        - [ ] Do that
        ...
    validations:
      required: true
  - type: textarea
    id: further-information
    attributes:
      label: Further Information
      description: Add additional helpful, issue-related information, such as, links, screenshots, sketches, considerations, thoughts, etc.
      placeholder: Helpful information
  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: Add a bullet point list of related issues that contains one or more entries. It has to contain, at least, the original issue that introduced the feature you want to change.
      placeholder: |
        - #42
        - #73
        ...
    validations:
      required: true
