name: Maintenance
description: Refactor specifically concerning adaption to updates of dependencies, target platforms, etc.
title: "maintenance: "
labels: ["maintenance"]
assignees: []
body:
  - type: textarea
    id: object-of-interest
    attributes:
      label: Object of Interest
      description: Describe the parts that require maintenance as specific as possible.
      placeholder: Which packages/libraries/tools/etc. are outdated/need updates/have to be reconfigured/etc.?
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Describe why the mentioned parts require maintenance as detailed as possible.
      placeholder: What released a new version/update (with breaking changes)? Did they release new, useful, project-relevant features? Was it a security update?
    validations:
      required: true
  - type: textarea
    id: solution-proposal
    attributes:
      label: Solution Proposal
      description: Describe the solution that you have in mind as detailed as possible.
      placeholder: To which version should which parts be upgraded? How should which parts be reconfigured?
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe potential side effects of your solution proposal, which could cause follow-up issues (in particular maintenance requests), to the best of your knowledge.
      placeholder: Could my solution proposal cause other problems?
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specify the acceptance criteria as a task list that contains one or more entries.
      placeholder: |
        - [ ] Do this
        - [ ] Do that
        ...
    validations:
      required: true
  - type: textarea
    id: further-information
    attributes:
      label: Further Information
      description: Add additional helpful, issue-related information, such as, links, screenshots, sketches, considerations, thoughts, etc.
      placeholder: Helpful information
  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: Add a bullet point list of other related issues, in case there are any.
      placeholder: |
        - #42
        - #73
        ...
