name: Pipeline
description: Improvements to the CI/CD pipeline
title: "pipeline: "
labels: ["pipeline"]
assignees: []
body:
  - type: textarea
    id: object-of-interest
    attributes:
      label: Object of Interest
      description: Describe the pipeline parts that require overwork as specific as possible.
      placeholder: Which stage(s) are affected?
    validations:
      required: true
  - type: textarea
    id: problem-motivation
    attributes:
      label: Problem/Motivation
      description: Describe your problem or motivation that caused your pipeline request as detailed as possible.
      placeholder: Was the pipeline slow? Did/ Why did the pipeline fail?
    validations:
      required: true
  - type: textarea
    id: solution-proposal
    attributes:
      label: Solution Proposal
      description: Describe the solution that you have in mind as detailed as possible.
      placeholder: How could the pipeline finish faster? How could the pipeline work again?
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe potential side effects of your solution proposal, which could cause follow-up issues (in particular pipeline requests), to the best of your knowledge.
      placeholder: Could my solution proposal cause other problems?
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specify the acceptance criteria as a task list that contains one or more entries.
      placeholder: |
        - [ ] Do this
        - [ ] Do that
        ...
    validations:
      required: true
  - type: textarea
    id: further-information
    attributes:
      label: Further Information
      description: Add additional helpful, issue-related information, such as, links, screenshots, sketches, considerations, thoughts, etc.
      placeholder: Helpful information
  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: Add a bullet point list of other related issues, in case there are any. In particular, the issue(s) (if you can narrow it/them down) that introduced the need for a pipeline request would be helpful.
      placeholder: |
        - #42
        - #73
        ...
