name: Testing
description: Improvements to the test suite, as well as pointing out wrong or missing tests
title: "testing: "
labels: ["testing"]
assignees: []
body:
  - type: textarea
    id: object-of-interest
    attributes:
      label: Object of Interest
      description: Describe the test suite parts/ the tests that require overwork as specific as possible.
      placeholder: Where are tests wrong/incomplete/missing? Where could the test suite be improved?
    validations:
      required: true
  - type: textarea
    id: problem-motivation
    attributes:
      label: Problem/Motivation
      description: Describe your problem or motivation that caused your testing request as detailed as possible.
      placeholder: Why do tests seem wrong/incomplete/missing? Why does the test suite need an improvement?
    validations:
      required: true
  - type: textarea
    id: solution-proposal
    attributes:
      label: Solution Proposal
      description: Describe the solution that you have in mind as detailed as possible.
      placeholder: How would you write the tests? How could the test suite be improved?
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe potential side effects of your solution proposal, which could cause follow-up issues (usually only relevant when suggesting changes to the test suite), to the best of your knowledge.
      placeholder: Could my solution proposal cause other problems?
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specify the acceptance criteria as a task list that contains one or more entries.
      placeholder: |
        - [ ] Do this
        - [ ] Do that
        ...
    validations:
      required: true
  - type: textarea
    id: further-information
    attributes:
      label: Further Information
      description: Add additional helpful, issue-related information such as links, screenshots, sketches, considerations, thoughts, etc.
      placeholder: Helpful information
  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: Add a bullet point list of other related issues, in case there are any. In particular, the issue(s) (if you can narrow it/them down) that introduced the need for a testing request would be helpful.
      placeholder: |
        - #42
        - #73
        ...
