name: Text Correction
description: Refactor of any bad language/wrong text implications and grammar/punctuation/spelling fixes, etc.
title: "text-correction: "
labels: ["text-correction"]
assignees: []
body:
  - type: textarea
    id: object-of-interest
    attributes:
      label: Object of Interest
      description: Describe the parts that require a text correction as specific as possible.
      placeholder: Where is bad language in use? Where does text imply something wrong? Where are grammar/punctuation/spelling/etc. mistakes?
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Describe why the current choice of words was bad/which other implications the text carries, or name which language rules the text violates.
      placeholder: Why is it considered bad language? What other things does the text imply? What kind of other mistakes does the text contain (grammar/punctuation/spelling/etc.)?
    validations:
      required: true
  - type: textarea
    id: solution-proposal
    attributes:
      label: Solution Proposal
      description: Write how you would write the text or at least name the essential points.
      placeholder: Improved text
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specify the acceptance criteria as a task list that contains one or more entries.
      placeholder: |
        - [ ] Do this
        - [ ] Do that
        ...
    validations:
      required: true
  - type: textarea
    id: further-information
    attributes:
      label: Further Information
      description: Add additional helpful, issue-related information, such as, links, screenshots, sketches, considerations, thoughts, etc.
      placeholder: Helpful information
  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: Add a bullet point list of other related issues, in case there are any.
      placeholder: |
        - #42
        - #73
        ...
