name: test krm

on:
  workflow_call:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: kustomize setup
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: "5.0.0"
      - name: test krm resources
        run: |
            for dir in $(ls -1 kustomize/overlays)
            do
              kustomize build kustomize/overlays/$dir
            done
